In [1]:
## Data Encoding

# Nominal/OHE Encoding
# Label/Ordinal Encoding
# Target Guided Ordinal Encoding

In [2]:
# OHE - One Hot Encoding --- Disadvantages
# Should not use when we have too many categories, cause it will lead to creation of tooo many features
# Second is Sparse Matrix --- again if there are many categories, the model can lead to overfit a particular feature(created from OHE (since it will have almost 0 and then very less 1))

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
## Simple DataFrame
df=pd.DataFrame({"color":["red","blue","green","green","red","blue"]})

In [5]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [6]:
encoder=OneHotEncoder()

In [15]:
# Fit -> Transform (We also have combination of both of them)
encoded=encoder.fit_transform(df[["color"]]).toarray()
# Alphabetically the feature got created blue - green - red

In [16]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [17]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
# for new data
encoder.transform([["blue"]]).toarray()

c:\Users\agarw\OneDrive\Desktop\Revision\Python\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [21]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [22]:
import seaborn as sns

In [23]:
df=sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [26]:
ohe=OneHotEncoder()

In [28]:
encoded_value=ohe.fit_transform(df[["sex"]]).toarray()

In [29]:
sex_df=pd.DataFrame(encoded_value,columns=ohe.get_feature_names_out())
sex_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [30]:
final_df=pd.concat([df,sex_df],axis=1)
final_df

     total_bill   tip     sex smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0       0.0
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0       0.0

[244 rows x 9 columns]

In [34]:
final_df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [35]:
# One Hot Encoding with Day
new_encoder=OneHotEncoder()

In [38]:
encoded_values=new_encoder.fit_transform(final_df[["day"]]).toarray()

In [39]:
day_encoded_df=pd.DataFrame(encoded_values,columns=new_encoder.get_feature_names_out())
day_encoded_df

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [40]:
final_df=pd.concat([final_df,day_encoded_df],axis=1)

In [41]:
final_df

     total_bill   tip     sex smoker  ... day_Fri day_Sat  day_Sun  day_Thur
0         16.99  1.01  Female     No  ...     0.0     0.0      1.0       0.0
1         10.34  1.66    Male     No  ...     0.0     0.0      1.0       0.0
2         21.01  3.50    Male     No  ...     0.0     0.0      1.0       0.0
3         23.68  3.31    Male     No  ...     0.0     0.0      1.0       0.0
4         24.59  3.61  Female     No  ...     0.0     0.0      1.0       0.0
..          ...   ...     ...    ...  ...     ...     ...      ...       ...
239       29.03  5.92    Male     No  ...     0.0     1.0      0.0       0.0
240       27.18  2.00  Female    Yes  ...     0.0     1.0      0.0       0.0
241       22.67  2.00    Male    Yes  ...     0.0     1.0      0.0       0.0
242       17.82  1.75    Male     No  ...     0.0     1.0      0.0       0.0
243       18.78  3.00  Female     No  ...     0.0     0.0      0.0       1.0

[244 rows x 13 columns]