In [1]:
import pandas as pd

In [9]:
# Pandas Series - 1D array like object that can hold any datatype
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [10]:
# Create Series from Dict Elements
data={"a":1,"b":2,"c":3}
series_d=pd.Series(data)
print(series_d)
print(type(series_d))

a    1
b    2
c    3
dtype: int64
<class 'pandas.Series'>

In [11]:
data=[10,20,30,40]
index=["A","B","C","D"]
series_i=pd.Series(data,index=index)
print(series_i)
print(type(series_i))

A    10
B    20
C    30
D    40
dtype: int64
<class 'pandas.Series'>

In [13]:
# DataFrame - 2D Heterogeneous Tabular Data (Multiple Rows and Columns)
# Creating DataFrame from dictionary of list
d={
    "id":[1,2,3,4],
    "name":["Hritik","Krish","John","Andy"],
    "age":[25,30,35,40]
   }
dataframe=pd.DataFrame(d)
print(dataframe)
print(type(dataframe))

   id    name  age
0   1  Hritik   25
1   2   Krish   30
2   3    John   35
3   4    Andy   40
<class 'pandas.DataFrame'>

In [15]:
import numpy as np
np.array(dataframe)

array([[1, 'Hritik', 25],
       [2, 'Krish', 30],
       [3, 'John', 35],
       [4, 'Andy', 40]], dtype=object)

In [17]:
# Create a DataFrame from List of Dictionaries
data=[
    {"id":1,"name":"Hritik","age":27},
    {"id":2,"name":"Krish","age":35},
    {"id":3,"name":"Andrez","age":29}
    ]
df=pd.DataFrame(data)
print(df)
print(type(df))

   id    name  age
0   1  Hritik   27
1   2   Krish   35
2   3  Andrez   29
<class 'pandas.DataFrame'>

In [20]:
df["name"]

0    Hritik
1     Krish
2    Andrez
Name: name, dtype: str

In [25]:
df.loc[0]

id           1
name    Hritik
age         27
Name: 0, dtype: object

In [26]:
df.iloc[0]

id           1
name    Hritik
age         27
Name: 0, dtype: object

In [27]:
df

   id    name  age
0   1  Hritik   27
1   2   Krish   35
2   3  Andrez   29

In [28]:
df.at[1,"age"]

np.int64(35)

In [29]:
df.iat[2,2]

np.int64(29)

In [30]:
df

   id    name  age
0   1  Hritik   27
1   2   Krish   35
2   3  Andrez   29

In [31]:
# Data Manipulation with DataFrames

df

   id    name  age
0   1  Hritik   27
1   2   Krish   35
2   3  Andrez   29

In [32]:
# Adding new column salary
df["Salary"]=[50000,60000,70000]
df

   id    name  age  Salary
0   1  Hritik   27   50000
1   2   Krish   35   60000
2   3  Andrez   29   70000

In [36]:
# Remove a column
df.drop("Salary",axis=1,inplace=True)

In [37]:
df

   id    name  age
0   1  Hritik   27
1   2   Krish   35
2   3  Andrez   29

In [38]:
df["age"]=df["age"]+1
df

   id    name  age
0   1  Hritik   28
1   2   Krish   36
2   3  Andrez   30

In [39]:
df.drop(0,inplace=True)
df

   id    name  age
1   2   Krish   36
2   3  Andrez   30