In [341]:
# How much work need to do related to EDA and Feature Engineering
## Data Cleaning for proper model training

# Difficult Dataset - Flight Price Prediction (Clean and EDA)

In [342]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [343]:
df=pd.read_excel("flight_price.xlsx",sheet_name="Sheet1")

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [344]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [345]:
## Column by Column every feature we will be cleaning it

In [346]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [347]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [348]:
## Handle Date of Journey (Separate Date Month and Year Separately)

In [349]:
## Feature Engineering
df["Date"]=df["Date_of_Journey"].str.split("/").str[0]

In [350]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01

In [351]:
df["Month"]=df["Date_of_Journey"].str.split("/").str[1]
df["Year"]=df["Date_of_Journey"].str.split("/").str[2]

In [352]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [353]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 1.1+ MB

In [354]:
df["Date"]=df["Date"].astype(int)
df["Month"]=df["Month"].astype(int)
df["Year"]=df["Year"].astype(int)

In [355]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [356]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 1.1 MB

In [357]:
## Now I can drop the Date of Journey column
#df.drop("Date_of_Journey",axis=1,inplace=True)
df.drop(columns=["Date_of_Journey"],inplace=True)

In [358]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [359]:
## Other Way

df["Arrival_Time"]=df["Arrival_Time"].apply(lambda x:x.split(" ")[0])

In [360]:
## How can we take out time from Arrival Time ( We can take out the hr and min parts)

df["Arrival_hour"]=df["Arrival_Time"].str.split(":").str[0]

In [361]:
df["Arrival_minute"]=df["Arrival_Time"].str.split(":").str[1]

In [362]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [363]:
#df["Arrival_Minute"]=df["Arrival_minute"].str.split(" ").str[0]

In [364]:
#df.head()

In [365]:
# df.drop(columns=["Arrival_minute"],inplace=True)
# df.head()

In [366]:
#df.rename(columns={"Arrival_Minute":"Arrival_minute"},inplace=True)

In [367]:
#df.head()

In [368]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Arrival_Time     10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_hour     10683 non-null  object
 14  Arrival_minute   10683 non-null  object
dtypes: int64(4), object(2), str(9)
memory usage: 1.2+ MB

In [369]:
df["Arrival_hour"]=df["Arrival_hour"].astype(int)
df["Arrival_minute"]=df["Arrival_minute"].astype(int)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Arrival_Time     10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_hour     10683 non-null  int64
 14  Arrival_minute   10683 non-null  int64
dtypes: int64(6), str(9)
memory usage: 1.2 MB

In [370]:
df.drop(columns=["Arrival_Time"],inplace=True)

In [371]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [372]:
# Handling Departure Time
df["Departure_hour"]=df["Dep_Time"].str.split(":").str[0]
df["Departure_minute"]=df["Dep_Time"].str.split(":").str[1]

In [373]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [374]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  str
 1   Source            10683 non-null  str
 2   Destination       10683 non-null  str
 3   Route             10682 non-null  str
 4   Dep_Time          10683 non-null  str
 5   Duration          10683 non-null  str
 6   Total_Stops       10682 non-null  str
 7   Additional_Info   10683 non-null  str
 8   Price             10683 non-null  int64
 9   Date              10683 non-null  int64
 10  Month             10683 non-null  int64
 11  Year              10683 non-null  int64
 12  Arrival_hour      10683 non-null  int64
 13  Arrival_minute    10683 non-null  int64
 14  Departure_hour    10683 non-null  object
 15  Departure_minute  10683 non-null  object
dtypes: int64(6), object(2), str(8)
memory usage: 1.3+ MB

In [375]:
df["Departure_hour"]=df["Departure_hour"].astype(int)
df["Departure_minute"]=df["Departure_minute"].astype(int)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  str
 1   Source            10683 non-null  str
 2   Destination       10683 non-null  str
 3   Route             10682 non-null  str
 4   Dep_Time          10683 non-null  str
 5   Duration          10683 non-null  str
 6   Total_Stops       10682 non-null  str
 7   Additional_Info   10683 non-null  str
 8   Price             10683 non-null  int64
 9   Date              10683 non-null  int64
 10  Month             10683 non-null  int64
 11  Year              10683 non-null  int64
 12  Arrival_hour      10683 non-null  int64
 13  Arrival_minute    10683 non-null  int64
 14  Departure_hour    10683 non-null  int64
 15  Departure_minute  10683 non-null  int64
dtypes: int64(8), str(8)
memory usage: 1.3 MB

In [376]:
df.drop(columns=["Dep_Time"],inplace=True)
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [377]:
df["Total_Stops"].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [378]:
df[df["Total_Stops"].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [379]:
df["Total_Stops"].mode()

0    1 stop
Name: Total_Stops, dtype: str

In [380]:
df["Total_Stops"]=df["Total_Stops"].map({"non-stop":0,
                                                 "1 stop":1,
                                                 "2 stops":2,
                                                 "3 stops":3,
                                                 "4 stops":4,
                                                 np.nan:1
                                                 })

In [381]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50

In [382]:
#df.drop(columns=["Total_Stops_Cleaned"],inplace=True)

In [383]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50

In [384]:
df["Total_Stops"].info()

<class 'pandas.Series'>
RangeIndex: 10683 entries, 0 to 10682
Series name: Total_Stops
Non-Null Count  Dtype
--------------  -----
10683 non-null  int64
dtypes: int64(1)
memory usage: 83.6 KB

In [385]:
# Route has 2 Source and Destination (we already have those features we can drop this)
df.drop(columns=["Route"],inplace=True)

In [386]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50

In [387]:
#df["Duration"]=df["Duration"].str.split("")

In [388]:
#df.head()

In [389]:
df["Duration"].str.split("h").str[0]

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: Duration, Length: 10683, dtype: object

In [390]:
df["Duration_hour"]=df["Duration"].str.split("h").str[0]

In [391]:
df["Duration_minute"]=df["Duration"].str.split(" ").str[1].str.split("m").str[0]

In [392]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  str
 1   Source            10683 non-null  str
 2   Destination       10683 non-null  str
 3   Duration          10683 non-null  str
 4   Total_Stops       10683 non-null  int64
 5   Additional_Info   10683 non-null  str
 6   Price             10683 non-null  int64
 7   Date              10683 non-null  int64
 8   Month             10683 non-null  int64
 9   Year              10683 non-null  int64
 10  Arrival_hour      10683 non-null  int64
 11  Arrival_minute    10683 non-null  int64
 12  Departure_hour    10683 non-null  int64
 13  Departure_minute  10683 non-null  int64
 14  Duration_hour     10683 non-null  object
 15  Duration_minute   9651 non-null   object
dtypes: int64(9), object(2), str(5)
memory usage: 1.3+ MB

In [393]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,Duration_hour,Duration_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,45

In [394]:
df["Duration_minute"]=df["Duration_minute"].fillna(0)

In [395]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,Duration_hour,Duration_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,45

In [396]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  str
 1   Source            10683 non-null  str
 2   Destination       10683 non-null  str
 3   Duration          10683 non-null  str
 4   Total_Stops       10683 non-null  int64
 5   Additional_Info   10683 non-null  str
 6   Price             10683 non-null  int64
 7   Date              10683 non-null  int64
 8   Month             10683 non-null  int64
 9   Year              10683 non-null  int64
 10  Arrival_hour      10683 non-null  int64
 11  Arrival_minute    10683 non-null  int64
 12  Departure_hour    10683 non-null  int64
 13  Departure_minute  10683 non-null  int64
 14  Duration_hour     10683 non-null  object
 15  Duration_minute   10683 non-null  object
dtypes: int64(9), object(2), str(5)
memory usage: 1.3+ MB

In [397]:
# df["Duration_hour"]=df["Duration_hour"].astype(int)
# #df["Duration_minute"]=df["Duration_minute"].astype(int)

In [398]:
# df[df["Duration_hour"]=="5m"]

In [399]:
# "5m".split(" ")

In [400]:
def splithour(s):
    split=s.split(" ")
    if(len(split)>=2 or "h" in split[0]):
        return int(split[0].split("h")[0])
    else:
        return 0

In [401]:
splithour("10h 50m")

10

In [402]:
def splitminute(s):
    split=s.split(" ")
    if(len(split)<2):
        if("m" in split[0]):
            return int(split[0].split("m")[0])
        else:
            return 0
    else:
        return int(split[1].split("m")[0])

In [403]:
splitminute("10h 5m")

5

In [404]:
df["Duration_hour"]=df["Duration"].apply(splithour)

In [405]:
df["Duration_minute"]=df["Duration"].apply(splitminute)

In [406]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,Duration_hour,Duration_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,45

In [407]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           10683 non-null  str
 1   Source            10683 non-null  str
 2   Destination       10683 non-null  str
 3   Duration          10683 non-null  str
 4   Total_Stops       10683 non-null  int64
 5   Additional_Info   10683 non-null  str
 6   Price             10683 non-null  int64
 7   Date              10683 non-null  int64
 8   Month             10683 non-null  int64
 9   Year              10683 non-null  int64
 10  Arrival_hour      10683 non-null  int64
 11  Arrival_minute    10683 non-null  int64
 12  Departure_hour    10683 non-null  int64
 13  Departure_minute  10683 non-null  int64
 14  Duration_hour     10683 non-null  int64
 15  Duration_minute   10683 non-null  int64
dtypes: int64(11), str(5)
memory usage: 1.3 MB

In [408]:
df["Total_Duration_Minutes"]=df["Duration_hour"]*60+df["Duration_minute"]

In [409]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,Duration_hour,Duration_minute,Total_Duration_Minutes
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25,445
2,Jet Airways,Delhi,Cochin,19h,2,No info,13882,9,6,2019,4,25,9,25,19,0,1140
3,IndiGo,Kolkata,Banglore,5h 25m,1,No info,6218,12,5,2019,23,30,18,5,5,25,325
4,IndiGo,Banglore,New Delhi,4h 45m,1,No info,13302,1,3,2019,21,35,16,50,4,45,285

In [410]:
df.drop(columns="Duration",inplace=True)

In [411]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,Duration_hour,Duration_minute,Total_Duration_Minutes
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,10,22,20,2,50,170
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,13,15,5,50,7,25,445
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,4,25,9,25,19,0,1140
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,23,30,18,5,5,25,325
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,21,35,16,50,4,45,285

In [412]:
df["Airline"].unique()

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [413]:
# We can do One Hot Encoding here

df["Source"].unique()

<StringArray>
['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai']
Length: 5, dtype: str

In [414]:
df["Destination"].unique()

<StringArray>
['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad']
Length: 6, dtype: str

In [415]:
df["Additional_Info"].unique()

<StringArray>
[                     'No info',  'In-flight meal not included',
 'No check-in baggage included',              '1 Short layover',
                      'No Info',               '1 Long layover',
              'Change airports',               'Business class',
               'Red-eye flight',               '2 Long layover']
Length: 10, dtype: str

In [416]:
from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder()

In [417]:
encoded_data=encoder.fit_transform(df[["Airline","Source","Destination","Additional_Info"]]).toarray()

In [418]:
ohe_df=pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out())

In [419]:
# All I need to do is merge with the above dataset and then drop the original columns
# Then it will be ready to be trained

final_df=pd.concat([df,ohe_df],axis=1)

In [420]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,13,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [421]:
final_df.drop(columns=["Airline","Source","Destination","Additional_Info"],inplace=True)

In [422]:
final_df.iloc[0]

Total_Stops                                        0.0
Price                                           3897.0
Date                                              24.0
Month                                              3.0
Year                                            2019.0
Arrival_hour                                       1.0
Arrival_minute                                    10.0
Departure_hour                                    22.0
Departure_minute                                  20.0
Duration_hour                                      2.0
Duration_minute                                   50.0
Total_Duration_Minutes                           170.0
Airline_Air Asia                                   0.0
Airline_Air India                                  0.0
Airline_GoAir                                      0.0
Airline_IndiGo                                     1.0
Airline_Jet Airways                                0.0
Airline_Jet Airways Business                       0.0
Airline_Multiple carriers                          0.0
Airline_Multiple carriers Premium economy          0.0
Airline_SpiceJet                                   0.0
Airline_Trujet                                     0.0
Airline_Vistara                                    0.0
Airline_Vistara Premium economy                    0.0
Source_Banglore                                    1.0
Source_Chennai                                     0.0
Source_Delhi                                       0.0
Source_Kolkata                                     0.0
Source_Mumbai                                      0.0
Destination_Banglore                               0.0
Destination_Cochin                                 0.0
Destination_Delhi                                  0.0
Destination_Hyderabad                              0.0
Destination_Kolkata                                0.0
Destination_New Delhi                              1.0
Additional_Info_1 Long layover                     0.0
Additional_Info_1 Short layover                    0.0
Additional_Info_2 Long layover                     0.0
Additional_Info_Business class                     0.0
Additional_Info_Change airports                    0.0
Additional_Info_In-flight meal not included        0.0
Additional_Info_No Info                            0.0
Additional_Info_No check-in baggage included       0.0
Additional_Info_No info                            1.0
Additional_Info_Red-eye flight                     0.0
Name: 0, dtype: float64

In [423]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 45 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10683 non-null  int64
 1   Price                                         10683 non-null  int64
 2   Date                                          10683 non-null  int64
 3   Month                                         10683 non-null  int64
 4   Year                                          10683 non-null  int64
 5   Arrival_hour                                  10683 non-null  int64
 6   Arrival_minute                                10683 non-null  int64
 7   Departure_hour                                10683 non-null  int64
 8   Departure_minute                              10683 non-null  int64
 9   Duration_hour                                 10683 non-null  int64
 10  Duration_minute                               10683 non-null  int64
 11  Total_Duration_Minutes                        10683 non-null  int64
 12  Airline_Air Asia                              10683 non-null  float64
 13  Airline_Air India                             10683 non-null  float64
 14  Airline_GoAir                                 10683 non-null  float64
 15  Airline_IndiGo                                10683 non-null  float64
 16  Airline_Jet Airways                           10683 non-null  float64
 17  Airline_Jet Airways Business                  10683 non-null  float64
 18  Airline_Multiple carriers                     10683 non-null  float64
 19  Airline_Multiple carriers Premium economy     10683 non-null  float64
 20  Airline_SpiceJet                              10683 non-null  float64
 21  Airline_Trujet                                10683 non-null  float64
 22  Airline_Vistara                               10683 non-null  float64
 23  Airline_Vistara Premium economy               10683 non-null  float64
 24  Source_Banglore                               10683 non-null  float64
 25  Source_Chennai                                10683 non-null  float64
 26  Source_Delhi                                  10683 non-null  float64
 27  Source_Kolkata                                10683 non-null  float64
 28  Source_Mumbai                                 10683 non-null  float64
 29  Destination_Banglore                          10683 non-null  float64
 30  Destination_Cochin                            10683 non-null  float64
 31  Destination_Delhi                             10683 non-null  float64
 32  Destination_Hyderabad                         10683 non-null  float64
 33  Destination_Kolkata                           10683 non-null  float64
 34  Destination_New Delhi                         10683 non-null  float64
 35  Additional_Info_1 Long layover                10683 non-null  float64
 36  Additional_Info_1 Short layover               10683 non-null  float64
 37  Additional_Info_2 Long layover                10683 non-null  float64
 38  Additional_Info_Business class                10683 non-null  float64
 39  Additional_Info_Change airports               10683 non-null  float64
 40  Additional_Info_In-flight meal not included   10683 non-null  float64
 41  Additional_Info_No Info                       10683 non-null  float64
 42  Additional_Info_No check-in baggage included  10683 non-null  float64
 43  Additional_Info_No info                       10683 non-null  float64
 44  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(33), int64(12)
memory usage: 3.7 MB