In [1]:
import numpy as np

In [5]:
## Create Arrays using numpy
## Create 1D Array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [8]:
arr2=np.array([[1,2,3,4,5]])
print(arr2.shape)

(1, 5)

In [ ]:
## 2D Array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)

(2, 5)

In [11]:
## In built Functions
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Identity Matrix/Array
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number of dimensions: 2
Size (number of elements): 10
Data type: int64
Item size (in bytes): 8

In [21]:
## Numpy Vectorized Operations

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arr1+arr2)
## Element wise addition
print("Subtraction:",arr1-arr2)
## Element wise multiplication
print("Multiplication:",arr1*arr2)
## Element wise division
print("Division",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]

In [24]:
## Universal Functions
arr=np.array([2,3,4,5,6])
## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sin
print(np.sin(arr))

## Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

In [25]:
## Array Slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [27]:
arr[0][0]

np.int64(1)

In [28]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [30]:
## Modify Array Elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

In [31]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]

In [33]:
## Statistical Concept
## Normalization
# Data change to have mean of 0 and standard dev of 1

data=np.array([1,2,3,4,5])
mean=np.mean(data)
stddev=np.std(data)

normalized_data= (data-mean)/stddev
print("Normalized Data :\n",normalized_data)

Normalized Data :
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [35]:
data=np.arange(1,11)
print(data)
#Mean
print(np.mean(data))
#Median
print(np.median(data))
#Std
print(np.std(data))
#Variance
print(np.var(data))

[ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5
2.8722813232690143
8.25

In [46]:
## Logical Operations
data=np.arange(1,11)
print(data)
print(data>5)
data[(data>=5) & (data<=8)]

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]

array([5, 6, 7, 8])

In [16]:
import pandas as pd
df=pd.read_excel("hospital_data_set.xls")
total=0
disease=set(df["diseases"])
for i in disease:
    total_pd=df[df["diseases"]==i]
    Male=total_pd[total_pd["gender"]=="M"]["id"].count()
    Female=total_pd[total_pd["gender"]=="F"]["id"].count()
    total+=Male+Female
    print(i,"\n","Male Count",Male,"\n","Female Count",Female)
print(len(df["id"]))
print(total)

Swine Flu
 Male Count 132
 Female Count 265
Fever
 Male Count 4360
 Female Count 8712
Cold
 Male Count 5852
 Female Count 16921
Diabetes
 Male Count 5603
 Female Count 175
PCOS
 Male Count 3817
 Female Count 0
Blood Pressure
 Male Count 1096
 Female Count 2
46935
46935

In [20]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 46935 entries, 0 to 46934
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46935 non-null  int64
 1   name      46935 non-null  str
 2   dob       46935 non-null  object
 3   phone     46935 non-null  int64
 4   emal      46935 non-null  str
 5   pid       46935 non-null  int64
 6   gender    46935 non-null  str
 7   diseases  46935 non-null  str
 8   age       46935 non-null  object
dtypes: int64(3), object(2), str(4)
memory usage: 3.2+ MB

(46935, 9)

In [21]:
df.describe()

                 id         phone           pid
count  46935.000000  4.693500e+04  4.693500e+04
mean   34578.000000  1.234568e+09  1.111135e+09
std    13549.111779  0.000000e+00  1.354911e+04
min    11111.000000  1.234568e+09  1.111111e+09
25%    22844.500000  1.234568e+09  1.111123e+09
50%    34578.000000  1.234568e+09  1.111135e+09
75%    46311.500000  1.234568e+09  1.111146e+09
max    58045.000000  1.234568e+09  1.111158e+09

In [22]:
# Data Manipulation and Analysis with Python

import pandas as pd

In [23]:
df=pd.read_csv("data.csv")
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [24]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     str
 1   Category  50 non-null     str
 2   Value     47 non-null     float64
 3   Product   50 non-null     str
 4   Sales     46 non-null     float64
 5   Region    50 non-null     str
dtypes: float64(2), str(4)
memory usage: 2.5 KB

In [29]:
df[df.isnull().any(axis=1)]

          Date Category  Value   Product  Sales Region
11  2023-01-12        B   60.0  Product2    NaN   West
15  2023-01-16        C    NaN  Product1  895.0  North
17  2023-01-18        C    NaN  Product1  108.0   West
28  2023-01-29        B    NaN  Product3  617.0  North
33  2023-02-03        C   27.0  Product3    NaN   East
35  2023-02-05        B   60.0  Product2    NaN   West
37  2023-02-07        C    2.0  Product1    NaN  North

In [ ]:
df.isnull().any(axis=0)

'df.isnull' is not recognized as an internal or external command,
operable program or batch file.

In [36]:
df.notnull().all(axis=0)

Date         True
Category     True
Value       False
Product      True
Sales       False
Region       True
dtype: bool

In [40]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [42]:
df_filled_na=df.fillna(0)

In [43]:
### Filling Missing Values with the Mean of the column
df["Sales_FilledNA"]=df["Sales"].fillna(df["Sales"].mean())

In [48]:
df.head()

         Date Category  Value   Product  Sales Region  Sales_FilledNA
0  2023-01-01        A   28.0  Product1  754.0   East           754.0
1  2023-01-02        B   39.0  Product3  110.0  North           110.0
2  2023-01-03        C   32.0  Product2  398.0   East           398.0
3  2023-01-04        B    8.0  Product1  522.0   East           522.0
4  2023-01-05        B   26.0  Product3  869.0  North           869.0

In [50]:
# Rename columns
# Date --> Sales Date
df=df.rename(columns={"Date":"Sale Date"})
print(df.head())

    Sale Date Category  Value   Product  Sales Region  Sales_FilledNA
0  2023-01-01        A   28.0  Product1  754.0   East           754.0
1  2023-01-02        B   39.0  Product3  110.0  North           110.0
2  2023-01-03        C   32.0  Product2  398.0   East           398.0
3  2023-01-04        B    8.0  Product1  522.0   East           522.0
4  2023-01-05        B   26.0  Product3  869.0  North           869.0

In [70]:
# Change Data types
# fillna Value with mean then
# Value --> Int
df.isna().sum(axis=0)

df["Value_int"]=df["Value"].fillna(df["Value"].mean()).astype(int)
df.head(20)

,Sale Date,Category,Value,Product,Sales,Region,Sales_FilledNA,Value_int
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,28
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,39
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,32
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,8
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,26
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,54
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,16
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,89
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,37
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,22
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,7
11,2023-01-12,B,60.0,Product2,NaN,West,557.130435,60
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,70
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,69
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,47
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,51
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,93
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,51
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,31
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,59

In [72]:
# New Col : 2*value
# use lambda and apply function on series
df["Value_Double"]=df["Value_int"].apply(lambda x:x*2)
df.head(20)

,Sale Date,Category,Value,Product,Sales,Region,Sales_FilledNA,Value_int,Value_Double
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,28,56
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,39,78
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,32,64
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,8,16
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,26,52
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,54,108
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,16,32
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,89,178
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,37,74
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,22,44
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,7,14
11,2023-01-12,B,60.0,Product2,NaN,West,557.130435,60,120
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,70,140
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,69,138
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,47,94
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,51,102
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,93,186
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,51,102
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,31,62
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,59,118

In [77]:
# Data Agg and Grouping
#Group by Product and get the mean

grouped_prod_mean=df.groupby("Product")["Value"].mean()
grouped_prod_mean
#type(grouped_prod_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [79]:
grouped_prod_reg_mean=df.groupby(["Product","Region"])["Value"].mean()

In [80]:
grouped_prod_reg_mean

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [81]:
grouped_agg=df.groupby("Region")["Value"].agg(["mean","max","median","count","sum"])
print(grouped_agg)

             mean   max  median  count     sum
Region
East    42.307692  97.0    32.0     13   550.0
North   37.666667  71.0    39.0      9   339.0
South   62.000000  94.0    66.5      8   496.0
West    61.588235  99.0    60.0     17  1047.0

In [83]:
# Merging and Joining Dataframes
df1=pd.DataFrame({"Key":["A","B","C"],"Value1":[1,2,3]})
df2=pd.DataFrame({"Key":["A","B","D"],"Value2":[2,4,6]})

df_merged=pd.merge(df1,df2,on="Key",how="inner")
print(df_merged)

  Key  Value1  Value2
0   A       1       2
1   B       2       4

In [84]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [85]:
df2

  Key  Value2
0   A       2
1   B       4
2   D       6

In [87]:
df_merged=pd.merge(df1,df2,on="Key",how="inner")
df_merged

  Key  Value1  Value2
0   A       1       2
1   B       2       4

In [88]:
df_merged=pd.merge(df1,df2,on="Key",how="outer")
df_merged

  Key  Value1  Value2
0   A     1.0     2.0
1   B     2.0     4.0
2   C     3.0     NaN
3   D     NaN     6.0

In [89]:
df_merged=pd.merge(df1,df2,on="Key",how="left")
df_merged

  Key  Value1  Value2
0   A       1     2.0
1   B       2     4.0
2   C       3     NaN

In [90]:
df_merged=pd.merge(df1,df2,on="Key",how="right")
df_merged

  Key  Value1  Value2
0   A     1.0       2
1   B     2.0       4
2   D     NaN       6

In [10]:
import pandas as pd
from io import StringIO

s = '[{"employee_name":"Jason","email":"jason@kach.in"}]'

df = pd.read_json(StringIO(s))

print(df)

  employee_name          email
0         Jason  jason@kach.in

In [16]:
df.to_json(orient="records")

'[{"employee_name":"Jason","email":"jason@kach.in"}]'

In [4]:
import pandas as pd
df=pd.read_html("https://financialservices.gov.in/beta/en/private-sector-Bank-page",header=None)

In [5]:
df[1]

,0,1,2
0,7,Federal Bank Ltd.,https://www.federalbank.co.in/
1,8,HDFC Bank Ltd,https://www.hdfcbank.com/
2,9,ICICI Bank Ltd.,https://www.icicibank.com/
3,10,Induslnd Bank Ltd,https://www.indusind.com/in/en/personal.html
4,11,IDFC First Bank Ltd,https://www.idfcfirstbank.com/
5,12,Jammu & Kashmir Bank Ltd.,https://www.jkbank.com/
6,13,Karnataka Bank Ltd.,https://karnatakabank.com/
7,14,Karur Vysya Bank Ltd,https://www.kvb.co.in/
8,15,Kotak Mahindra Bank Ltd.,https://www.kotak.com/en/home.html
9,16,Lakshmi Vilas Bank Ltd,https://www.lvbank.com/
10,17,Nainital Bank Ltd.,https://www.nainitalbank.co.in/
11,18,RBL Bank Ltd.,https://www.rblbank.com/
12,19,South Indian Bank Ltd.,https://www.southindianbank.com/
13,20,Tamilnad Mercantile Bank Ltd.,https://www.tmb.in/
14,21,YES Bank Ltd.,https://www.yesbank.in/
15,22,IDBI Bank Ltd.,https://www.idbibank.in/